### ISSUE TITLE
carga redsys.png

### ISSUE THREAD

**Issue by karrikas** [jesusangel/wc-sermepa#11]
Hola Jesús Ángel, 

He visto que en determinadas situaciones la imagen de redsys que aparece en el proceso de compra no funciona. Por ejemplo con determinadas configuraciones en wpml o si se cambia la configuración de wp-content. 

Creo que sería mejor hacer la carga de la imagen de la siguiente forma:

```
$this->icon = apply_filters( 'wc_redsys_icon',  plugins_url( '/assets/images/icons/redsys.png', __FILE__ ) );

```
En lugar de:
```
$this->icon = apply_filters( 'wc_redsys_icon',  home_url() . '/wp-content/plugins/' . dirname( plugin_basename( __FILE__ ) ) . '/assets/images/icons/redsys.png' );
```

Excelente trabajo con el plugin. 

Muchas gracias,

**Comment by jesusangel** [comment]
Muchas gracias por la aportación. La incorporaré en la próxima
actualización.
