### ISSUE TITLE
Actuallizar para Wordpress 4.5 / Woocommerce 2.5

### ISSUE THREAD

**Issue by alexfloren** [jesusangel/wc-sermepa#13]
Con la ultima version de Wordpress y Woocommerce, el plugin no aparece en la pestaña "Finalizar Compra" como pasarela de pago. 

Ruta: Woocommerce > Ajustes > Finalizar compra

**Comment by jesusangel** [comment]
Hola.

Gracias por avisar. Intentaré ver que pasa este fin de semana.

Saludos cordiales.

**Comment by alexfloren** [comment]
Hola, has encontrado una solución?

**Comment by jesusangel** [comment]
Hola.

He instalado un Wordpress 4.5.2 y un Woocommerce 2.5.5 junto con mi plugin
de pago vía Redsys y sí que me aparece en las opciones de Woocommerce.

¿Activaste el plugin después de instalarlo? ¿Tienes algún otro plugin para Wordpress relacionado con pagos?

Saludos cordiales.

**Comment by jesusangel** [comment]
Hola.

He instalado un Wordpress 4.5 y un Woocommerce 2.5.5 junto con mi plugin
de pago vía Redsys y sí que me aparece en las opciones de Woocommerce.

¿Lo has activado?

Saludos cordiales.
