### ISSUE TITLE
E-mail de confirmación de compra no me llega con https

### ISSUE THREAD

**Issue by epmunoz** [jesusangel/wc-sermepa#15]
Hola!

En primer lugar, muchas gracias por el módulo! supongo que será un problema mío de configuración, pero me gustaría que me ayudarais a encontrar la respuesta.

Cuando instalé el módulo en la web, no tenía https y el e-mail de confirmación de pedido estaba llegando correctamente. Hace poco le pusimos el https y el e-mail no se envía, quedando además el estado del pedido en "Pending" en lugar de en "Processing".
Al principio pensaba que era porque el valor de la variable "Callback" estaba en "http", pero al cambiarlo a "https" me pasa lo mismo.

¿Será que la dirección del callback está mal? ¿Cómo puedo saber cuál es la correcta? ¿Se debe cambiar algo en el panel de administración del TPV al pasar la web a funcionar con https?

Muchas gracias!

**Comment by jesusangel** [comment]
Hola.

¿Podrías activar el log, hacer una operación de prueba, y enviármelo?

Saludos cordiales.

**Comment by epmunoz** [comment]
El log le tengo activado y he hecho una operación de prueba, pero no encuentro el archivo... La ruta es en wp-content/plugins/woocommerce/ no? y ahí debería aparecer la carpeta logs si no me equivoco,  pero no me aparece nada... O estoy mirando en el sitio que no es?

**Comment by epmunoz** [comment]
He mirado dentro del tema que existe otra carpeta woocommerce y tampoco aparece... qué raro

**Comment by fromcouch** [comment]
Hola @epmunoz 

Los logs deberian ir en 

    /wp-content/plugins/woocommerce/logs

Pero por alguna razon que no logro comprender a mi se me ponen en 

    /wp-content/uploads/wc-logs/

A ver si los encuentras ahi.

Un Saludo,

**Comment by epmunoz** [comment]
Gracias @fromcouch efectivamente están ahí.

@jesusangel Te lo adjunto por correo, ya que no me dejaba adjuntarlo aquí. 

Saludos

**Comment by jesusangel** [comment]
Respondo públicamente por si le sirve a más gente, ya que he intercambiado emails de forma privada.

Creo que el problema se debe a que el servidor que aloja el sitio de Pablo usa SNI para compartir una IP para múltiples certificados SSL y que la pasarela de Redsys no soporta dicho protocolo (SNI). Estoy casi seguro de que esto es así.

La solución entonces es permitir las conexiones no cifradas (HTTP) al sitio web e indicar a la pasarela que nos notifique vía HTTP. Tengo pendiente modificar el plugin para poder seleccionar el protocolo de notificación. A ver si tengo un rato este fin de semana y saco una nueva versión.

Saludos cordiales.

**Comment by epmunoz** [comment]
Muchas gracias @jesusangel Ya he notificado a Redsys... a ver que me dicen. Os voy contando!

**Comment by jesusangel** [comment]
Estoy subiendo una nueva versión del plugin (1.0.11) que permite seleccionar el protocolo con el que la pasarela de Redsys envía la notificación del pago. Salvo que tengáis un sitio con IP dedicada (algo no muy habitual en los alojamientos compartidos), debéis seleccionar HTTP y permitir a la pasarela de Redsys conectarse mediante dicho protocolo.

Existe un mecanismo para compartir una IP entre varios sitios que usan SSL llamado SNI (Server Name Indication), pero en estos momentos la pasarela de Redsys no soporta dicho mecanismo y cuando se conecta a vuestro sitio por HTTS el certificado SSL que recibe es el genérico del servidor (normalmente el correspondiente al panel de control de administración) y la notificación del pago falla porque dicho certificado no es válido para vuestra tienda.
