### ISSUE TITLE
Pagos Recurrentes

### ISSUE THREAD

**Issue by fromcouch** [jesusangel/wc-sermepa#17]
Hola Jesus

un cliente me ha pedido si seria facil, duplicando o modificando, activar los pagos recurrentes a traves del modulo de redsys.

Si me das unas directrices creo el fork y lo hago yo mismo. Solo necesito saber cual es la mejor via o que debo tener en cuenta si duplico el plugin (se que es una burrada, lo se)

Gracias

**Comment by jesusangel** [comment]
Hola.

Lo único que deberías tener en cuenta es que la nueva funcionalidad sea
genérica y se integre bien con la actual. En su día estuve mirando por
encima la funcionalidad de los pagos recurrentes, pero no vi una forma
sencilla de implementarlo.

Lo cierto es que es algo no muy frecuente en las tiendas online. Tal vez
sea mejor hacer un plugin a medida para estos casos.

No sé cual será tu caso, pero imagino que, al hacer la primera compra
(supongo que será una suscripción) hay que indicar en los datos del pago
que se envían a Redsys que se va a hacer un pago recurrente. En algunos
casos esto será siempre así, mientras que en otros puede depender del
producto que se compre (puede haber productos que tengan un formato de
suscripción y otros que sean de pago único).

Por último, la tienda deberá tener otra parte para cargar los pagos
sucesivos. Al hacer el primer pago deberás guardar la referencia de
Redsys para hacer los siguientes cargos y deberás tener una tarea que se
ejecute periódicamente y que haga los cargos cuando corresponda.

Hablo de memoria.

Resumiendo, si ves que se te complica mucho lo que puedes hacer es
copiar lo que necesites y montar tu propio plugin.

Espero haberte ayudado.

Saludos cordiales.

**Comment by fromcouch** [comment]
Si me has ayudado, muchas gracias.
Tengo que mirar la documentación de Redsys porque la idea es un pago en x veces. Es un producto caro (600€) y esperaba que redsys gestionara la recurrencia de los 6 pagos. Sino es asi sera un follon. Estamos mirando el woocommerce subscriptions pero no se si cumple los requisitos.

Muchas Gracias, me has dado un buen punte de partida.

Un Saludo,

**Comment by jesusangel** [comment]
Ah! Lo que quieres hacer entonces es fraccionar el pago. En teoría creo
que se podría hacer con los pagos recurrentes. No obstante, debes tener
en cuenta que este tipo de operativa la tiene que aprobar antes el
banco. No todos los clientes de TPV Virtual pueden usar esa
funcionalidad, debe autorizarte la entidad bancaria. Mira bien la
documentación de Redsys, había varias modalidades de pago.

Saludos cordiales.

**Comment by fromcouch** [comment]
Lo miro, 

Gracias

**Comment by robertglez** [comment]
Hola,

Os quería preguntar si ha habido algún avance para esta funcionalidad o si @fromcouch consiguió hacerlo. Estoy interesado en hacer exactamente lo mismo, poder crear un pago fraccionado para un producto.

Gracias!

**Comment by fromcouch** [comment]
Hola @robertglez 

al final se instalo el woocommerce subscriptions.

Un Saludo,

**Comment by robertglez** [comment]
De acuerdo @fromcouch, muchas gracias.

Muy bueno saber que se puede hacer de esa manera mediante woocommerce subscriptions, sin necesidad de rizar el rizo complejizándolo desde el lado de la pasarela de pago.

Saludos!

**Comment by fromcouch** [comment]
Hola @robertglez 

la verdad es que no te se decir como acabo porque se lo manejo solo el cliente. Pero ante la duda y para que quede constancia le pregunto y posteo en cuanto tenga la respuesta.

Un Saludo,

**Comment by buqueinsignia** [comment]
Hola @fromcouch y @robertglez 

¿Conseguisteis finalmente integrar Woocommerce Subscriptions con la pasarela de pago de Redsys de Jose Conti?
Yo no consigo que se muestre al finalizar la compra, aún estando activa en toda la tienda. Es muy raro.

Gracias!
