### ISSUE TITLE
Error 404 una vez el pago a finalizado

### ISSUE THREAD

**Issue by zapa-gentoo** [jesusangel/wc-sermepa#19]
Hola.

Antes que nada, darte las gracias por tu tiempo en crear este plugin para la comunidad.

Estoy teniendo un problema. Al darle a 'continuar' despues de finalizar el pago, que tendria que devolvernos al woocommerce dando las gracias por la compra y demás, aparece un error 404...

La url a la que redirecciona es esta:

http://www.dominio.com/finalizar-comprar/616/order-received/616?key=wc_order_577cea5092e34&utm_nooverride=1&Ds_SignatureVersion=HMAC_SHA256_V1&Ds_MerchantParameters=eyJEc19EYXRlIjoiMDYlMkYwNyUyRjIwMTYiLCJEc19Ib3VyIjoiMTMlM0EzMiIsIkRzX1NlY3VyZVBheW1lbnQiOiIxIiwiRHNfQW1vdW50IjoiMzEwMCIsIkRzX0N1cnJlbmN5IjoiOTc4IiwiRHNfT3JkZXIiOiIwMDAwMDYxNjMxNDYiLCJEc19NZXJjaGFudENvZGUiOiIxMjY1NTE5MDIiLCJEc19UZXJtaW5hbCI6IjAwMSIsIkRzX1Jlc3BvbnNlIjoiMDAwMCIsIkRzX1RyYW5zYWN0aW9uVHlwZSI6IjAiLCJEc19NZXJjaGFudERhdGEiOiI1ZTc5MWY5ODJlMzUyOGY1NWQ1MjQ4NWY2YTg3OGQ4NjE0NDRlOTNhIiwiRHNfQXV0aG9yaXNhdGlvbkNvZGUiOiIzMTg5MzAiLCJEc19Db25zdW1lckxhbmd1YWdlIjoiMSIsIkRzX0NhcmRfQ291bnRyeSI6IjcyNCJ9&Ds_Signature=0HDJ1Mfegqapd2ZeAR9AgxytoY70KhgCb6m3eQXJ3io=

Cuando realmente a la que tendria que redireccionar es a esta: 
(si modifico a mano la url en la barra de direcciones y pongo esta, aparece el mensaje del resumen del pedido..)

http://www.dominio.com/finalizar-comprar/order-received/616?key=wc_order_577cea5092e34&utm_nooverride=1&Ds_SignatureVersion=HMAC_SHA256_V1&Ds_MerchantParameters=eyJEc19EYXRlIjoiMDYlMkYwNyUyRjIwMTYiLCJEc19Ib3VyIjoiMTMlM0EzMiIsIkRzX1NlY3VyZVBheW1lbnQiOiIxIiwiRHNfQW1vdW50IjoiMzEwMCIsIkRzX0N1cnJlbmN5IjoiOTc4IiwiRHNfT3JkZXIiOiIwMDAwMDYxNjMxNDYiLCJEc19NZXJjaGFudENvZGUiOiIxMjY1NTE5MDIiLCJEc19UZXJtaW5hbCI6IjAwMSIsIkRzX1Jlc3BvbnNlIjoiMDAwMCIsIkRzX1RyYW5zYWN0aW9uVHlwZSI6IjAiLCJEc19NZXJjaGFudERhdGEiOiI1ZTc5MWY5ODJlMzUyOGY1NWQ1MjQ4NWY2YTg3OGQ4NjE0NDRlOTNhIiwiRHNfQXV0aG9yaXNhdGlvbkNvZGUiOiIzMTg5MzAiLCJEc19Db25zdW1lckxhbmd1YWdlIjoiMSIsIkRzX0NhcmRfQ291bnRyeSI6IjcyNCJ9&Ds_Signature=0HDJ1Mfegqapd2ZeAR9AgxytoY70KhgCb6m3eQXJ3io=

He estado buceando por tu código pero no encuentro donde poder modificar esta URL.
No sé si tiene algo que ver pero nuestro sitio implementa el plugin multilenguaje 'polylang'.

¿Como puedo solucionar esto?
Muchas gracias.
Un saludo.

**Comment by jesusangel** [comment]
Hola.

Revisa las opciones generales de tu Wordpress. Seguramente tengas
configurado dominio.com como URL del sitio. Revisa también las
traducciones, algunas URL del proceso de compra deben traducirse.

Saludos cordiales.

**Comment by zapa-gentoo** [comment]
Hola de nuevo y gracias por tu respuesta.

Perdona por el mensaje anterior...cuando indicaba "dominio.com" me referia al dominio de mi pagina web. En el primer mensaje reemplacé mi dominio por "dominio.com" pero en el segundo link se me olvido reemplazarlo :S.

Creo que el problema como te comenté anteriormente esta aqui: /finalizar-comprar/616/order-received/616.

El 616 es el numero de pedido, pero creo que el primer /616/  no deberia estar, ya que si lo elimino a mano en la barra de direcciónes, aparece el mensaje del resumen de compra sin problema. Creo que deberia ser: /finalizar-comprar/order-received/616/.



Saludos.

**Comment by jesusangel** [comment]
Hola.

Disculpa el retraso. La URL de vuelta cuando el pago se ha realizado
correctamente se calcula llamando al método get_return_url heredado de
la clase WC_Payment_Gateway (línea 475 de
wc_redsys_payment_gateway.php).

Revisa la configuración de Woocommerce a ver por qué aparece dos veces
el número de orden.

Saludos cordiales.

**Comment by jesusangel** [comment]
¿Diste con la solución?
