### ISSUE TITLE
Pedidos quedan pendientes de pago

### ISSUE THREAD

**Issue by aureliopons** [jesusangel/wc-sermepa#26]
Hola, gracias por tu plugin. Lo he instalado a la primera y todo ok, pero los pedidos me quedan pendientes de pago. 

En el terminal de Bankia todo parece correcto, se recibe el pago y luego en la lista de notificaciones indica que ha enviado la notificacion a esta dirección: https://www........com/?wc-api=WC_MyRedsys  y que se ha recibido correcta. Ademas en el log del woocommerce me aparece como recibida, y el pedido se crea bien.

Es simplemente que no lo marca como pagado.  ¿Se te ocurre por que puede ser?

Muchisimas gracias

**Comment by jesusangel** [comment]
Hola.

Seguramente tu hosting comparta la IP con otros sitios y por tanto use
SNI para identificar el certificado SSL. Debes permitir que las
conexiones desde la pasarela de Sermepa se hagan por HTTP.

Saludos cordiales.

**Comment by aureliopons** [comment]
Agradezco mucho tu respuesta, es casi seguro que aunque tengo SSL la IP esta compartida. 

Mil Gracias
