### ISSUE TITLE
Pedidos pendientes de pago

### ISSUE THREAD

**Issue by carlosperez1930** [jesusangel/wc-sermepa#28]
Muy buenas.

Muchas gracias por su plugin, estoy mu contento por que funcionó todo a la primera.

La única cuestión que tenía es el por que los pedidos aunque se cobren siempre se quedan pendientes de pago, supongo que es alguna configuración del redsys pero no consigo saber cual.

¿Alguien sería tan amable de ayudarme?

Muchas gracias y un saludo :)

**Comment by jesusangel** [comment]
Estimado Carlos.

Lo más probable es que la pasarela de Redsys no pueda conectarse a tu tienda online para notificar la recepción del pago. Esto puede deberse a varias causas. Tal vez algún plugin de seguridad esté bloqueando la conexión, o bien tu sitio usa SSL con SNI (típico de los hostings compartidos que usan una única IP con varios certificados) y la pasarela de Redsys no soporta aún SNI.

Para saber el motivo, debes echar un vistazo al log de la pasarela de tu banco, donde podrás ver el código de error que se produce al intentar hacer la notificación del pago.

Saludos cordiales

**Comment by carlosperez1930** [comment]
Exactamente usamos una SSL, entonces no hay solución de momento no?

Un saludo :)

**Comment by jesusangel** [comment]
Sí. Añadir una regla para permitir a la pasarela conectarse por HTTP.

**Comment by jesusangel** [comment]
Cierro el caso. Si tienes alguna duda puedes abrirlo de nuevo.

**Comment by carlosperez1930** [comment]
@jesusangel y como se hace eso?

Gracias :)

**Comment by jesusangel** [comment]
Hola.

Antes de nada, asegúrate de que has seleccionado el valor "HTTP" para la opción "Protocolo para notificaciones".

Después la cosa depende de la configuración de tu sitio. Si permites navegar por tus páginas mediante el protocolo HTTP no tendrás que hacer nada más. Si por el contrario tienes alguna regla que redirecciona las conexiones no seguras a la versión segura (HTTPS) entonces tendrás que añadir una excepción para que dicha regla no afecte a la siguiente URL:

http://tusitioweb.tudominio/?wc-api=WC_MyRedsys

Saludos cordiales.
