### ISSUE TITLE
Errores al actualizar a WC 3

### ISSUE THREAD

**Issue by xarkitu** [jesusangel/wc-sermepa#29]
Hola Jesus Angel,

Te remito fallo en la pasarela al pedir el id de la orden, deberia ser algo así:

```
379			/**
			 * Get Redsys Args for passing to the TPV server
			 *
			 * @access public
			 * @param mixed $order
			 * @return array
			 */
			function get_redsys_args( $order ) {
				
				// FIX by SUGO
				$order_id = version_compare( WC_VERSION, '2.7', '<' ) ? $order->id : $order->get_id() ;
```

Esta linea tambien da error : 

`$products .= $separator . $cart_content['quantity'] . 'x' . $cart_content['data']->post->post_title;`

Edito:

Arreglado con:

```
$title = version_compare( WC_VERSION, '2.7', '<' ) ? $cart_content['data']->post->post_title : $cart_content['data']->get_title();
$products .= $separator . $cart_content['quantity'] . 'x' . $title;

```

Saludos y gracias por tu trabajo 👍

**Comment by jesusangel** [comment]
Hola.

¿Qué error te da el plugin con Woocommerce 3? Acabo de probarlo y a mi sí que me funciona.
Aunque puede ser mejor leer el ID de la compra con el método get_id, este atributo se declara como protegido en la clase padre WC_Data y como tal puede ser accedido directamente desde la clase heredada WC_Order.

Con la segunda línea pasa algo parecido.

¿Te aparece un error o es algún tipo de notificación? ¿Qué versión de PHP estás usando?

Saludos cordiales.

**Comment by xarkitu** [comment]
Hola Jesus Angel,

No es un error como tal, es una notificación de WC3 advirtiendo el acceso a un atributo protegido.

El plugin sigue funcionando, pero dejará de hacerlo en cuanto quiten la compatibilidad hacia atrás y te llena el registro de avisos.

No es problema de php o mala codificación.

Para depuración, no se si lo conoces, te recomiendo https://es.wordpress.org/plugins/query-monitor/

Saludos cordiales.

**Comment by jesusangel** [comment]
Hola.

Muchas gracias por el apunte del plugin, no lo conocía.
Ya que los desarrolladores de Woocommerce se han molestado en añadir métodos get/set para las propiedades, habrá que usarlos :-)

Saludos cordiales.
