### ISSUE TITLE
Issue woocommerce redsys

### ISSUE THREAD

**Issue by rafaeljesusvera** [jesusangel/wc-sermepa#30]
Hello, i set up the redsys plugin. It is asking me all the time about a SCH Key. I am very sure that the info is correct. But still asking me for that SCH key.

When I test the plugin in the web, an error occurs. It communicates with the bank. It asks me to verify the payment with a text in my phone, but before confirming, an error occurs and the transaction is not complete.

I have no idea how to fix it :-(

**Comment by jesusangel** [comment]
Please send some screenshots showing the errors.

**Comment by jesusangel** [comment]
No answer
