### ISSUE TITLE
Error SIS0019 Redsys - The Ds_Merchant_Amount is invalid.

### ISSUE THREAD

**Issue by carmenates09** [jesusangel/wc-sermepa#31]
The last Monday, July 31 2017, the plugin work fine, but yesterday it show me this error:

![image](https://user-images.githubusercontent.com/4367129/28978007-479e3bce-7912-11e7-97ab-eb5cf67f31ca.png)

Error Redsys: `<!--SIS0019:-->Error en datos enviados. Contacte con su comercio.</font></td>`
 
The error was on:
Wordpress Version 4.8.1 (**_the Monday it was 4.8.0_**)
PHP Version 7.1.1-1

**Comment by jbouza** [comment]
Gracias, ya se solucionó el problema

**Comment by victorcruz86** [comment]
The solution is perfect, I solved the problem.
