### ISSUE TITLE
Php Notice: status se llamo incorrectamente....

### ISSUE THREAD

**Issue by xarkitu** [jesusangel/wc-sermepa#36]
Hola!

No es error como tal, pero va dejando aviso.

Hay una llamada en la 720 a status de la orden que va a dejar de ser compatible.

```
// Check order not already completed
if ( $order->status == 'completed' ) {
```

Cuando pueda la cambia por...

```
// Check order not already completed
if ( $order->get_status() == 'completed' ) {
```

Saludos cordiales y gracias por el plugin!
Javier

**Comment by jesusangel** [comment]
Hola.

Hecho. También puedes desactivar los avisos (notices) de PHP en la configuración de éste para que no aparezcan en los logs.

Saludos cordiales.
