### ISSUE TITLE
error SIS0432: error in transferring data

### ISSUE THREAD

**Issue by LinnFrederix** [jesusangel/wc-sermepa#37]
Hallo,

We are making a website for a spanish company.

Their old website works with you plugin. When I install the plugin on the new website, I get error SIS0432: error in transferring data. Could you tell me how to resolve it?

![schermafbeelding 2018-01-26 om 09 33 36](https://user-images.githubusercontent.com/35833387/35431579-4b3c94d4-027d-11e8-8ff8-960217a36d2b.png)

**Comment by jesusangel** [comment]
Please, check the FUC number (commerce) in the plugin configuration.

**Comment by LinnFrederix** [comment]
The FUC number? In de settings of which plugin or were to find it. I don't see settings for your plugin and I don't find this description in woocommerce settings eather. Thank you

**Comment by jesusangel** [comment]
It's in the Woocommerce settings, in the payment gateways section.

**Comment by LinnFrederix** [comment]
Ok, it is the first time I use woocommerce. What is de FUC number than. If I look at the payment gateway I don't see it. So I really don't know what to do... En which number do I need for this. Is it someting like VAT?

**Comment by LinnFrederix** [comment]
Oeps, found it

**Comment by jesusangel** [comment]
Closed
