### ISSUE TITLE
Error sending parameters

### ISSUE THREAD

**Issue by aitorUdabe** [jesusangel/wc-sermepa#38]
Error, the same parameter is sent as the name of the owner and at the time of payment the name of the owner of the trade appears instead of the holder of the card.

**Comment by jesusangel** [comment]
Hola Aitor.

¿Cual es el problema? ¿Te aparece el nombre del comercio en lugar del propietario de la tarjeta? El nombre del cliente/titular de la tarjeta no se envía en los datos del pago, no es posible tal cosa. Fíjate en el código fuente de la página con el formulario de pago y busca algo como . Es el código del error. Dime cual es el que te aparece.

Saludos cordiales.

**Comment by aitorUdabe** [comment]
Hola Jesus,

El problema viene en la configuración del plugin. Cuando vamos ajustes y pago y pagar con tarjeta hay un campo que pone nombre del comercios dos veces esta repetido el primer campo hemos de dejarlo vacío, creo que ese campo deberíais eliminarlo ya que si rellenamos ese campo es el que se pasa como nombre del titular.

Aitor Udabe

Mov: +34 666 27 54 14
Email:aitoruudabe@gmail.com

**Comment by jesusangel** [comment]
Hecho. Siento el retraso.
