### ISSUE TITLE
No transmite el descuento a la pasarela de pago redsys

### ISSUE THREAD

**Issue by rinconvital** [jesusangel/wc-sermepa#39]
Hola Jesús, mil gracias por su aportación del plugin, facilita mucho.

Preguntarle si sabe que puede suceder sobre cuando "Desde el Back End" de woocommerce, en los detalles del pedido de 1 cliente donde se le ha aplicado Descuento, abro la ""Pagina de pago del cliente"" y  SI me aparece correctamente el descuento, pero cuando elijo Redsys y me lleva a la pasarela de pago, el monto a pagar NO contempla el descuento en el momento de introducir la tarjeta.

Agradezco mucho su ayuda,
Carmelo

**Comment by jesusangel** [comment]
Hola.

No sé por qué puede suceder eso, pero no creo que sea problema del plugin de pago, ya que éste transmite a RedSys el importe que le indica WooCommerce. Revisa la configuración de la tienda para ver si los cupones de descuento se están aplicando correctamente.

Saludos cordiales.
