### ISSUE TITLE
Duda funcionamiento

### ISSUE THREAD

**Issue by svilla16** [jesusangel/wc-sermepa#40]
Hola Jesús.
Agradezco el trabajo en el plugin, pero tengo una duda respecto al funcionamiento. Tengo una tienda basada en woocommerce y currency switcher para tener varais monedas en la tienda. Usamos tu plugin para pagar mediante redsys pero cuando tratamos de pagar en dolares no nos coge el valor en dolares sino en euros. Tiene algo que ver el plugin o es algo perteneciente a otros plugin?? Tanto woocommerce como el pago en redsys estan configurados para usar el euro pero queremos que se vea y trabaje en dolares en otros paises. Gracias por la ayuda y saudos

**Comment by jesusangel** [comment]
Hola.

Actualmente el plugin no soporta varias monedas. La configuración es fija y se hace en la zona de administración de Woocommerce.

Saludos cordiales.
