### ISSUE TITLE
Ds_ErrorCode:SIS0051;

### ISSUE THREAD

**Issue by ricardohoyos** [jesusangel/wc-sermepa#7]
Hola Jesús Angel, gracias por el plugin

Resulta que cuando un cliente llega a redsys y por alguna razón vuelve al carro y vuelve a pagar, redsys devuelve el error de pedido duplicado.
No tengo cacheadas las páginas de pago, pero es cierto que me vuelve a generar el mismo número de pedido y no hay forma de pagar.
¿conoces alguna solución para este bug?

Muchas gracias

**Comment by jesusangel** [comment]
Hola.

Lo que se puede hacer es añadir la fecha y hora al código del pedido. No
obstante, habría que revisar por qué la pasarela guarda el código de pedido
si no se hizo el pago. Hasta ahora nadie me había comentado este
comportamiento.

Saludos.

**Comment by ricardohoyos** [comment]
Al final he tenido que cambiar de plugin y no pasa, añade un número aleatorio cada vez que vuelves a darle al checkout

 

De: Jesús Ángel del Pozo [mailto:notifications@github.com] 
Enviado el: martes, 07 de abril de 2015 0:22
Para: jesusangel/wc-sermepa
CC: ricardohoyos
Asunto: Re: [wc-sermepa] Ds_ErrorCode:SIS0051; (#7)

 

Hola.

Lo que se puede hacer es añadir la fecha y hora al código del pedido. No
obstante, habría que revisar por qué la pasarela guarda el código de pedido
si no se hizo el pago. Hasta ahora nadie me había comentado este
comportamiento.

Saludos.

**Comment by MarinaGR** [comment]
Hola, muchas gracias por tu plugin!!

Hoy le ha sucedido a un cliente el mismo error SIS0051, aunque veo que hace un mes lo marcaste como solucionado (https://wordpress.org/support/topic/duplicate-order-no-error).

La versión que tenemos instalada de tu plugin es la última en este momento (v1.0.5) y la de woocommerce instalada en tienda es v2.3.8, no se si tendrá algo que ver.

Estoy extrañada, ya que tu solución de añadir time() al identificador del pedido es correcta. Además estoy intentando replicar el error y no lo consigo. ¿Se te ocurre que ha podido pasar?

¡Gracias!

**Comment by jesusangel** [comment]
Hola.

No estoy seguro. Si habías activado el log del plugin o si puedes revisar
el historial de pedidos en la zona de administración del TPV tal vez puedas
confirmar lo que ha pasado. Tal vez haya sido una coincidencia, creo que lo
que se añade es minutos y segundos, ¿podría haber hecho el pedido justo una
hora después? Ya sería mala suerte :-)

Tal vez haya recargado la página y enviado dos veces el mismo código de
pedido...

Saludos cordiales.

**Comment by MarinaGR** [comment]
Eso estaba pensando, que tal vez haya sido una coincidencia, porque me parece que se añaden sólo los 4 últimos números de time? Revisaré mañana más detenidamente.
Muchas gracias por la rapidez. 

Saludos,
Marina.

**Comment by MarinaGR** [comment]
Tenías razón, acabo de replicar el error al recargar la página del banco.
Por lo tanto nada que ver con el plugin. 

¡Gracias de nuevo!
