### ISSUE TITLE
Problema http / https

### ISSUE THREAD

**Issue by huracaniki** [jesusangel/wc-sermepa#8]
Buenas tardes, gracias por el plugin que he estado utilizando sin problemas.

El caso es que en una tienda, tengo metido un certificado y forzado el https en el fichero .htaccess.

Cuando hace la petición la hago normal al http me pone un codigo de error 302 en el menu de administración de redsys (movido temporalmete) .

Si lo hago por https me aparece un -1 Received fatal alert: handshake_failure

Que podría hacer para configurarlo correctamente?

gracias

**Comment by jesusangel** [comment]
Hola.

¿Estás usando un certificado emitido por alguna entidad certificadora o usas uno autofirmado? Parece que la pasarela de Redsys no soporta la redirección, pero debería funcionar al acceder al sitio mediante HTTPS. Una cosa que puedes hacer, si no tienes un certificado admitido por la pasarela, es añadir una condición a la redirección HTTPS para que no se aplique a las conexiones procedentes del banco. Lo puedes hacer tal vez por IP, o por URL.

Saludos.

**Comment by jesusangel** [comment]
¿Resolviste el problema?

**Comment by huracaniki** [comment]
Buenos días,

perdona que no te haya contestado antes. Finalmente lo que hice fue meter una excepción para que concretamente a esa URL no hiciera la redirección HTTPS y me funcionó correctamente.

Gracias, por lo demás el plugin perfecto.

Un saludo y gran trabajo.

**Comment by huracaniki** [comment]
Buenos días Jesus Angel,

le escribo en referencia al plugin que ha desarrado y por el que hemos hablado alguna vez. Estoy teniendo un problema relacionado con el http - https

En la parte del tpv el error que tengo es estes:

https://lecrane.com/?wc-api=WC_MyRedsys
-1 com.ibm.jsse2.util.j: No trusted certificate found

Hasta ahora me estaba funcionando correctamente, pero actualice plugins y core y template el lunes y me está dando estos problemas.

Anteriormente el resultado era:

http://lecrane.com/?wc-api=WC_MyRedsys
200

Crees que poniendo esto se solucionaría?

$this->notify_url = str_replace( 'http:', 'https:', add_query_arg( 'wc-api', 'WC_MyRedsys', home_url( '/' ) ) );

o bien con?

RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteCond %{QUERY_STRING} !wc-api [NC]

Gracias por su tiempo.

Un saludo

Manuel

**Comment by jesusangel** [comment]
Hola.

En tu caso tienes que poner:
$this->notify_url = str_replace( 'https:', 'http:', add_query_arg(
'wc-api', 'WC_MyRedsys', home_url( '/' ) ) );

O ver por qué la pasarela no acepta el certificado SSL de tu sitio.

Saludos cordiales.
