### ISSUE TITLE
Creo que este plugin no va funcionar después de 23/11/2015 (Cambios en TPV de redsys)

### ISSUE THREAD

**Issue by sumitpaulsmx** [jesusangel/wc-sermepa#9]
Hola Jesus. Primero de todo agradezco mucho tú trabajo que has hecho. Estoy utilizando este plugin desde hace un año y nunca me ha dado problemas.
Solamente te quiero avisar de que pronto redsys va remplazar el algoritmo SHA-1 en sus sistemas por  SHA256. 
¿Habrá actualización nueva pronto para suportar el SHA256?
https://canales.redsys.es/canales/ayuda/migracionSHA256.html
Gracias

**Comment by boquiabierto** [comment]
Gracias @sumitpaulsmx además veo que en el enlace que pones [hacen referencia](http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOItHS1dDT3dDTz9g82MDDzD_HyNfPwdDfwDDIAKInErcHczJ06_AQ7gaEBIf7h-FFiJh7-zu6FRsIGXu7mTJVCfoZOTQbCPgYGRCVQBPieCFeBxQ0FuaIRBpqciAJbEr50!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/) a un listado de plugins entre otros para Woocomerce. Probaré a ver que tal.

**Comment by sumitpaulsmx** [comment]
Ok Gracias.

**Comment by jesusangel** [comment]
Hola.

Sí. Este fin de semana sacaré la actualización.

Saludos cordiales.

**Comment by sumitpaulsmx** [comment]
(y) Gracias Jesus.

**Comment by jesusangel** [comment]
Hola.

He implementado la firma SHA256 en una nueva versión del plugin, pero no
puedo hacer pruebas porque no tengo una clave SHA256 para probar. Lo he
intentado con "Mk9m98IfEblmPfrpsawt7BmxObt98Jev" pero sin éxito.

¿Sabes si hay datos (FUC, terminal y clave SHA2) de prueba?

He dejado la nueva versión en: tel.abloque.com/wc_redsys.zip por si
quieres hacer pruebas. Ojo, que probablemente no funcionará.

Saludos.

**Comment by sumitpaulsmx** [comment]
Pues yo tampoco aun lo tengo entorno de pruebas para probar.
Pero cuando lo tenga intentare probar lo.
Muchas gracias

**Comment by jesusangel** [comment]
Es el entorno de pruebas el que me interesa. Mira a ver por favor cual es
la clave sha256 para dicho entorno.

**Comment by jesusangel** [comment]
Perdón. Creo que tu "lo" era un "no".

**Comment by sumitpaulsmx** [comment]
Utilizando estos datos:
	fuc="999008881";
	terminal="871";
	moneda="978";
	trans="0";
        clave=Mk9m98IfEblmPfrpsawt7BmxObt98Jev

Si llegas en la final de pagina donde se tiene que poner los datos de tarjeta de crédito sin ningún error eso significa que todo va bien.

**Comment by jesusangel** [comment]
Buenos días.

Esos son los datos con los que estaba probando, pero debe haber algún
error, pues con ellos tampoco funciona el plugin original de Redsys. El
error que da es el SYS0042 (error en la firma).

He comprobado que mi plugin genera la misma firma (para los mismos datos
de entrada) que el de Redsys, pero si la clave secreta no es la
adecuada, la pasarela de Redsys no considerará la firma como buena.

Les envié un email para preguntar. A ver si me responden hoy.

Saludos cordiales.

**Comment by sumitpaulsmx** [comment]
Utilizando api de redsys tal como viene funciona. 
Mira si el numero de pedido tiene como mínimo tiene la longitud de 4.

Gracias

**Comment by jesusangel** [comment]
Ok. Fallo mio. Estaba probando con el entorno Sis-t (el de test que
había usado otras veces) pero debía usar el Sis-d.
